directory_structure:
  # 0. 总类与系统文件
  "0. 总类与系统文件":
    "0.1 系统配置文件":
      - "0.1.1 操作系统配置"
      - "0.1.2 软件配置文件"
      - "0.1.3 注册表备份"
    "0.2 临时存储区":
      - "0.2.1 下载缓存区"
      - "0.2.2 跨设备中转文件"
      - "0.2.3 剪贴板历史存档"
    "0.3 未分类文件":
      - "0.3.1 待分析文件"
      - "0.3.2 碎片化内容"
      - "0.3.3 多属性交叉文件"
    "0.4 文件备份区":
      - "0.4.1 每日备份"
      - "0.4.2 每周备份"
      - "0.4.3 月度归档"
    "0.5 归档文件库":
      - "0.5.1 过期文档"
      - "0.5.2 历史版本"
      - "0.5.3 废弃资料"

  # 1. 个人与生活管理
  "1. 个人与生活管理":
    "1.1 证件证书":
      - "1.1.1 个人身份证件"
      - "1.1.2 学历/职业证书"
      - "1.1.3 财产权属证明"
    "1.2 家庭档案":
      - "1.2.1 户籍关系证明"
      - "1.2.2 房产车辆档案"
      - "1.2.3 重要物品清单"
    "1.3 日常记录":
      - "1.3.1 电子日记本"
      - "1.3.2 手写笔记扫描"
      - "1.3.3 灵感速记存档"
    "1.4 生活服务":
      - "1.4.1 物业单据"
      - "1.4.2 水电费记录"
      - "1.4.3 维修保养档案"
    "1.5 兴趣爱好":
      - "1.5.1 摄影作品"
      - "1.5.2 手作教程"
      - "1.5.3 收藏目录"

  # 2. 工作与职业发展（完整结构示例）
  "2. 工作与职业发展":
    "2.1 行业资料库":
      - "2.1.1 行业白皮书"
      - "2.1.2 竞品分析报告"
      - "2.1.3 法规政策汇编"
    "2.2 项目文档":
      - "2.2.1 项目计划书"
      - "2.2.2 会议纪要存档"
      - "2.2.3 交付成果终稿"
    "2.3 合同协议":
      - "2.3.1 劳动合同"
      - "2.3.2 商务合作协议"
      - "2.3.3 保密协议"
    "2.4 职业证书":
      - "2.4.1 资格认证"
      - "2.4.2 培训记录"
      - "2.4.3 考核成绩"
    "2.5 工作成果":
      - "2.5.1 作品集"
      - "2.5.2 案例库"
      - "2.5.3 项目总结"
    "2.6 工作日志": 
      - "2.6.1 日报"
      - "2.6.2 周报"

  # 3-9类结构（保持相同格式）
  "3. 学习与教育资源": 
    "3.1 学科资料":
    "3.2 课程资料":
    "3.3 学术论文":
  
  "4. 财务与资产管理": 
    "4.1 银行单据":
    "4.2 投资理财":
  
  # ...其他大类保持相同结构...

  # 9. 其他特殊类别
  "9. 其他特殊类别":
    "9.1 加密文件区":
      - "9.1.1 隐私数据"
      - "9.1.2 商业秘密"
      - "9.1.3 加密容器"
    "9.2 纪念资料库":
      - "9.2.1 重要时刻影像"
      - "9.2.2 书信手稿"
      - "9.2.3 数字纪念品"
    "9.3 待处理文件":
      - "9.3.1 临时草稿"
      - "9.3.2 待审核文件"
      - "9.3.3 转存队列"
    "9.4 共享协作区":
      - "9.4.1 团队共享"
      - "9.4.2 客户对接"
      - "9.4.3 公开资源"
    "9.5 虚拟机镜像":
      - "9.5.1 系统镜像"
      - "9.5.2 应用沙箱"
      - "9.5.3 实验环境"